# Generated by Django 4.1.1 on 2022-10-25 07:05

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_category', models.CharField(blank=True, max_length=10, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='foto/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='foodname',
            name='available_weight',
        ),
        migrations.RemoveField(
            model_name='foodname',
            name='food_consistence',
        ),
        migrations.RemoveField(
            model_name='foodname',
            name='food_maker',
        ),
        migrations.DeleteModel(
            name='AvailableWeight',
        ),
        migrations.DeleteModel(
            name='FoodConsistence',
        ),
        migrations.DeleteModel(
            name='FoodMaker',
        ),
        migrations.DeleteModel(
            name='FoodName',
        ),
    ]
